### ISSUE TITLE
Dotline Loader?

### ISSUE THREAD

**Issue by oyeanuj** [raulanatol/react-inline-loaders#79]
Hi @raulanatol, thank you for open sourcing this library! Just wondering if you were also planning to implement the 'dotline loader' from the linked codepen?

**Comment by raulanatol** [comment]
Hi @oyeanuj, thanks.
I've planning to implement all this loaders as soon as possible.
This loader will be the next.
Regards.

**Comment by raulanatol** [comment]
Hi @oyeanuj.
It's done http://natol.es/react-inline-loaders/#/demos/DotLineLoader

**Comment by oyeanuj** [comment]
Great, thank you!
